on:
  schedule:
    - cron: '45 5 * * 0,5,6'
      timezone: "Europe/Berlin"

jobs:
  miri:
    name: "Miri"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup

      - name: Install Dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libwayland-dev libxkbcommon-dev libxkbcommon-x11-dev libasound2-dev libudev-dev xvfb

      - name: Test with Miri
        run: cargo miri test
